# NODE 03    
plugins.security.ssl.transport.pemkey_filepath: /usr/share/opensearch/config/os04-key.pem # relative path
plugins.security.ssl.transport.pemcert_filepath: /usr/share/opensearch/config/os04.pem
plugins.security.ssl.transport.pemtrustedcas_filepath: /usr/share/opensearch/config/root-ca.pem
plugins.security.ssl.http.enabled: true
plugins.security.ssl.http.pemkey_filepath: /usr/share/opensearch/config/os04-key.pem
plugins.security.ssl.http.pemcert_filepath: /usr/share/opensearch/config/os04.pem
plugins.security.ssl.http.pemtrustedcas_filepath: /usr/share/opensearch/config/root-ca.pem
# With TLS client authentication enabled, REST clients can send a TLS certificate with the HTTP request to provide identity information to the Security plugin
plugins.security.ssl.http.clientauth_mode: OPTIONAL
plugins.security.audit.type: internal_opensearch
############## REST Management API configuration settings ##############
plugins.security.restapi.roles_enabled: ["all_access", "security_rest_api_access", "anomaly_full_access", "asynchronous_search_full_access", "index_management_full_access", "security_manager", "kibana_server"]
plugins.security.restapi.admin.enabled: true
# Updates the existing configuration using the REST API.
plugins.security.unsupported.restapi.allow_securityconfig_modification: true
# let a super admin (or a user with sufficient permissions to access this API) add, retrieve, update, or delete any distinguished names from an allow list to enable communication between clusters and/or nodes
plugins.security.nodes_dn_dynamic_config_enabled: true
plugins.security.system_indices.permission.enabled: true
plugins.security.system_indices.enabled: true
plugins.security.system_indices.indices:
  - ".plugins-ml-agent"
  - ".plugins-ml-config"
  - ".plugins-ml-connector"
  - ".plugins-ml-controller"
  - ".plugins-ml-model-group"
  - ".plugins-ml-model"
  - ".plugins-ml-task"
  - ".plugins-ml-conversation-meta"
  - ".plugins-ml-conversation-interactions"
  - ".plugins-ml-memory-meta"
  - ".plugins-ml-memory-message"
  - ".plugins-ml-stop-words"
  - ".opendistro-alerting-config"
  - ".opendistro-alerting-alert*"
  - ".opendistro-anomaly-results*"
  - ".opendistro-anomaly-detector*"
  - ".opendistro-anomaly-checkpoints"
  - ".opendistro-anomaly-detection-state"
  - ".opendistro-reports-*"
  - ".opendistro-notifications-*"
  - ".opendistro-notebooks"
  - ".opendistro-asynchronous-search-response*"
  - ".opensearch-notifications-*"
  - ".opensearch-notebooks"
  - ".opensearch-observability"
  - ".ql-datasources"
  - ".opendistro-asynchronous-search-response*"
  - ".replication-metadata-store"
  - ".opensearch-knn-models"
  - ".geospatial-ip2geo-data*"
  - ".plugins-flow-framework-config"
  - ".plugins-flow-framework-templates"
  - ".plugins-flow-framework-state"
plugins.security.authcz.admin_dn:
  - 'CN=admin,OU=DFCTI,O=NIPNE,L=Magurele,ST=ILFOV,C=RO'
#OpenSearch Security needs to identify requests between the nodes in the cluster. It uses node certificates to secure these requests
#The simplest way to configure node certificates is to list the Distinguished Names (DNs) of these certificates
plugins.security.nodes_dn:
  - 'CN=os01,OU=DFCTI,O=NIPNE,L=Magurele,ST=ILFOV,C=RO'
  - 'CN=os02,OU=DFCTI,O=NIPNE,L=Magurele,ST=ILFOV,C=RO'
  - 'CN=os03,OU=DFCTI,O=NIPNE,L=Magurele,ST=ILFOV,C=RO'
  - 'CN=os04,OU=DFCTI,O=NIPNE,L=Magurele,ST=ILFOV,C=RO'
  - 'CN=os05,OU=DFCTI,O=NIPNE,L=Magurele,ST=ILFOV,C=RO'
  - 'CN=dashboards,OU=DFCTI,O=NIPNE,L=Magurele,ST=ILFOV,C=RO'
http.detailed_errors.enabled: true