---
_meta:
  type: "internalusers"
  config_version: 2
admin:
  hash: "$2y$12$qQz2JKL6uIC1LZuU/jPUleofpFJJw3NJlbSn0T1Xtzc694yaF4Ghe"
  reserved: true
  backend_roles:
  - "admin"
  description: "Admin user"
dashboards:
  hash: "$2y$12$qQz2JKL6uIC1LZuU/jPUleofpFJJw3NJlbSn0T1Xtzc694yaF4Ghe"
  backend_roles:
  - "admin"
  - "dashboards"
  opendistro_security_roles:
  - "dashboards"
  description: "User that Dashboard will access OpenSearch"
kibanaserver:
  hash: "$2y$12$qQz2JKL6uIC1LZuU/jPUleofpFJJw3NJlbSn0T1Xtzc694yaF4Ghe"
  reserved: true
  description: "Demo kibanaserver user"  