---
_meta:
  type: "roles"
  config_version: 2

dashboards:
  hidden: false
  cluster_permissions:
  - cluster_all
  index_permissions:
  - index_patterns:
    - "*"
    allowed_actions:
    - crud
    - search
  tenant_permissions:
  - tenant_patterns:
    - "Global"
    allowed_actions:
    - "kibana_all_write"
  static: false